[package]
name = "bingo-sim"
version = "0.1.0"
edition = "2024"

[dependencies]
indicatif = "0.18.0"
plotters = "0.3.7"
rand = "0.9.2"
rayon = "1.11.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
sysinfo = "0.37.2"
