services:
  database:
    image: postgres:18.0
    restart: unless-stopped
    ports:
      - "5400:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      TZ: UTC
    volumes:
      - postgres_data:/var/lib/postgresql/18/docker

  api:
    image: ghcr.io/yourusername/wanbingo-api:latest
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      # Add other env vars as needed
    depends_on:
      - database

  app:
    image: ghcr.io/yourusername/wanbingo-frontend:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      # Add other env vars as needed

  caddy:
    image: caddy:2.4.6
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
      - api
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_SCHEDULE=0 2 * * 0-4
    restart: unless-stopped

volumes:
  caddy_data:
  postgres_data: