services:
  database:
    image: postgres:18.0
    restart: unless-stopped
    ports:
      - "5400:5432"
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: bingo
      TZ: UTC
    volumes:
      - postgres_data:/var/lib/postgresql/18/docker

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "9000:8080"
    depends_on:
      - database

  api:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    image: wanbingoapi:dev
    volumes:
      - ./server:/go/src/app
      - ./migrations:/go/src/app/migrations
    ports:
      - "8000:8000"
    env_file:
      - ./server/.env
    depends_on:
      - database

  app:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    image: wanbingoapp:dev
    ports:
      - "7999:7999"
    volumes:
      - ./frontend:/app
    env_file:
      - ./frontend/.env

  caddy:
    image: caddy:2.4.6
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
      - api
    volumes:
      - ./Caddyfile.dev:/etc/caddy/Caddyfile
      - caddy_data:/data

volumes:
  caddy_data:
  postgres_data:

