-- Seed data for core schema

-- Insert the "deleted user" placeholder account
INSERT INTO players (id, did, display_name, avatar, settings, score, permissions, created_at, updated_at)
VALUES ('DELETED',
        '0',
        '[Deleted User]',
        NULL,
        '{
          "system_account": true
        }'::jsonb,
        0,
        0,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       ('SYSTEM',
        '1',
        '[System]',
        NULL,
        '{
          "system_account": true
        }'::jsonb,
        0,
        0,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP);

-- Insert initial shows
INSERT INTO shows (id, youtube_id, scheduled_time, actual_start_time, thumbnail, metadata, created_at, updated_at, deleted_at)
VALUES ('OmipPXoq22', null, '2025-10-24 23:30:00.000000 +00:00', null,
        'https://pbs.floatplane.com/stream_thumbnails/5c13f3c006f1be15e08e05c0/519128595136666_1760744141891.jpeg', '{
    "title": "Pixel Phones Finally Blowing Up",
    "youtube": {
      "title": "Pixel Phones Finally Blowing Up - WAN Show October 17, 2025",
      "is_live": false,
      "upcoming": false,
      "video_id": null
    },
    "floatplane": {
      "title": "Pixel Phones Finally Blowing Up - WAN Show October 17, 2025",
      "is_wan": true,
      "is_live": false,
      "thumbnail": "https://pbs.floatplane.com/stream_thumbnails/5c13f3c006f1be15e08e05c0/519128595136666_1760744141891.jpeg",
      "is_thumbnail_new": false
    }
  }', '2025-10-10 23:46:40.000000 +00:00', '2025-10-18 09:19:41.312790 +00:00', null),
       ('Y2kz75uBC8', null, '2025-10-10 23:30:00.000000 +00:00', null,
        'https://pbs.floatplane.com/stream_thumbnails/5c13f3c006f1be15e08e05c0/733054221374526_1760139634263.jpeg', '{
          "title": "Hello Floatplane! - WAN Show October 17, 2025",
          "youtube": {
            "title": "Hello Floatplane! - WAN Show October 17, 2025",
            "is_live": false,
            "upcoming": false,
            "video_id": null
          },
          "floatplane": {
            "title": "Hello Floatplane! - WAN Show October 17, 2025",
            "is_wan": false,
            "is_live": false,
            "thumbnail": "https://pbs.floatplane.com/stream_thumbnails/5c13f3c006f1be15e08e05c0/733054221374526_1760139634263.jpeg",
            "is_thumbnail_new": false
          }
        }', '2025-10-10 23:46:40.000000 +00:00', '2025-10-17 22:20:28.791709 +00:00', null);

-- Insert initial tiles
INSERT INTO tiles (id, title, category, last_drawn)
VALUES ('pYhro7iTSQ', 'Linus or Luke or Dan sighs', 'Events', NOW()),
       ('3AXPH39mmU', 'Linus ignores Luke to change the topic', 'Linus', NOW()),
       ('kJdmP6gDSi', 'Linus hates on Twitch Chat', 'Linus', NOW()),
       ('ji3eCBLPrx', 'Linus Facepalms', 'Linus', NOW()),
       ('AQrAcWkqsg', 'Intro/Outro run accidentally', 'Set/Production', NOW()),
       ('W9No_ylM54', 'The microphone gets hit', 'Set/Production', NOW()),
       ('OPdeRADtmK', '*Wow, I feel old...*', 'Events', NOW()),
       ('jXurzTPKY_', 'Camera Not Focused', 'Set/Production', NOW()),
       ('GdOM4Jx7ZI', 'Luke was Wrong', 'Luke', NOW()),
       ('WH6tzRJ5PG', 'Linus Was Wrong', 'Linus', NOW()),
       ('U3SEvAZT4E', 'Colton Quit / Fired joke', 'Events', NOW()),
       ('kxR5uknbsW', 'Linus Drops Something', 'Linus', NOW()),
       ('LdaAhl25W4', 'Nvidia News!', 'Topics', NOW()),
       ('BaD8f-Qmpg', 'AMD News!', 'Topics', NOW()),
       ('RubFqyA_Zs', 'Intel News!', 'Topics', NOW()),
       ('lovN9OEyXu', 'Apple News!', 'Topics', NOW()),
       ('1zVBE4wLA9', 'New Sponsor!', 'Sponsors', NOW()),
       ('3LHG-WTzBz', 'Screenshare has No Audio', 'Set/Production', NOW()),
       ('fY2u7DoLZ7', 'Audio Clipping', 'Set/Production', NOW()),
       ('sBbnG8b1O_', 'Literally one super topic until sponsor spot', 'Sponsors', NOW()),
       ('nc9JZl99ME', 'Linus leaves the other host alone', 'Linus', NOW()),
       ('JAgGIaNECU', 'Video output not connected to laptop', 'Set/Production', NOW()),
       ('lND6zOabtj', 'Console Topic for the peasantry', 'Topics', NOW()),
       ('eb8uFT5T_K', 'Luke says *That''s Hilarious!*', 'Luke', NOW()),
       ('17U6OdT6QW', 'Someone messes with the set', 'Set/Production', NOW()),
       ('7zeqP0zUVd', 'Linus: ''We''ve got a great show for you today!''', 'Linus', NOW()),
       ('NZUFuGT4dg', 'No actual news before sponsor spot', 'Sponsors', NOW()),
       ('uRE41fjRbK', 'Linus doesn''t censor while swearing', 'Linus', NOW()),
       ('cjAULhjZBL', 'Motion-Sickness Camera', 'Set/Production', NOW()),
       ('69LrHZvYtE', 'Super-Zoomed Camera', 'Set/Production', NOW()),
       ('MdM9kwiAna', 'Hello Dan', 'Dan', NOW()),
       ('i27fmnr_tu', 'LTT Store Plug', 'Events', NOW()),
       ('u5jjt2ruMP', 'LTT Water Bottle drank from', 'Events', NOW()),
       ('JDJuwnV-OI', 'Banana For Scale', 'Events', NOW()),
       ('ftsUAzY_Db', 'Linus Hot Take', 'Linus', NOW()),
       ('A6NucRK2Gj', 'Linus Roasts a Company', 'Linus', NOW()),
       ('kJvJpGqFBV', 'Linus'' parenting stories', 'Linus', NOW()),
       ('KsG42jyeJu', 'Mispronunciation of a word/phrase', 'Events', NOW()),
       ('I3GA3iJPjt', 'Stream Dies', 'Events', NOW()),
       ('tj69a_JZfe', 'Costumes!', 'Events', NOW()),
       ('BfaqFYztlR', '4+ Hour WAN Show (What a Champ!)', 'Events', NOW()),
       ('ASPY0Qy1tZ', 'Luke laughs uncomfortably loud', 'Luke', NOW()),
       ('2wN544Mxvc', 'Luke talks about AI', 'Luke', NOW()),
       ('KKbzU2rbiJ', 'Accidentally shared confidential info', 'Events', NOW()),
       ('W-motMP4Zs', 'Dan ignores Linus', 'Dan', NOW()),
       ('lqnGNVc9nt', 'Hit me Dan', 'Dan', NOW()),
       ('c7BjRI697F', 'WANShow.bingo is mentioned', 'Events', NOW()),
       ('TBmEkuWwpR', 'Not my problem anymore, talk to the new ceo.', 'Events', NOW()),
       ('r9Mnf_ME0O', 'Linus: it''s not my fault', 'Linus', NOW()),
       ('8pce6MxeUu', 'Sponsored by dbrand!', 'Sponsors', NOW()),
       ('BlxEmS0DoW', 'Sponsored by SquareSpace!', 'Sponsors', NOW()),
       ('73KLQbGb8q', 'Linus eats/drinks something', 'Linus', NOW()),
       ('sljhxujZPi', 'Linus complains about YouTube', 'Linus', NOW()),
       ('trAzkzKWLx', 'Live Tech Product Unboxing', 'Events', NOW()),
       ('mfTNmsg6UI', 'Talking over Audio', 'Set/Production', NOW()),
       ('WeV8Fp5qTk', 'Trust me Bro', 'Events', NOW()),
       ('Qp6vz_-EAD', 'Linus is out of touch', 'Linus', NOW()),
       ('-Q5HcciRTE', 'Too long (15 min+) on a topic', 'Events', NOW()),
       ('jjhqqMEYt7', 'Too long (5 mins+) on a merch message', 'Events', NOW()),
       ('kBkO1ou5Mg', 'Innuendo', 'Events', NOW()),
       ('jEU-ZVrpBR', '*oh yeah I guess we should do sponsor spots*', 'Events', NOW()),
       ('BV1VTXBrjr', 'Linus rants while Luke interacts with chat bored', 'Linus', NOW()),
       ('DEVW39oIdq', 'Linus changes camera angle for dan ''I''ve got it''', 'Linus', NOW()),
       ('SSd2LAc9FQ', 'Linus: ''Since you put me on the spot''', 'Linus', NOW()),
       ('qMU9ISD_9Q', 'New merch launch', 'Events', NOW()),
       ('HhLMpqN2FA', 'Putting off Merch Messages ''We''ll get them in a sec''', 'Events', NOW()),
       ('bEFxAZvdfT', 'DAN tries to talk but is muted', 'Dan', NOW()),
       ('4ArJxjLxtv', 'DING', 'Events', NOW()),
       ('Yyb48SI0jU', 'Dennis overboard sponsorspot', 'Sponsors', NOW()),
       ('ukjQJ5_-CK', 'Going back to previous topic/merch message', 'Events', NOW()),
       ('hQ3vMD9xNl', '*The Hackening*', 'Events', NOW()),
       ('KeThW3a1tm', 'Luke struggles to pick a topic', 'Luke', NOW()),
       ('23Cv4gW6DY', '*Spicy Take*', 'Events', NOW()),
       ('X_335PYYBn', 'Dan cam with no Dan', 'Dan', NOW()),
       ('KVeHSSKAWk', 'Dan goes and gets snacks for Linus', 'Dan', NOW()),
       ('Avkh2dEj_R', 'Linus ''turns off'' Dan', 'Dan', NOW()),
       ('VKWvCKvn0s', '*Where was I going with this?*', 'Linus', NOW()),
       ('A4EhjSc-Fe', 'Luke doing a concern', 'Luke', NOW()),
       ('qvQmuF6SnJ', 'Linus rants for over 2 mins without input from Luke', 'Linus', NOW()),
       ('J6KHwBchwS', 'Dan goes AFK', 'Dan', NOW()),
       ('W97lSUnnJb', 'Mentions another creator', 'Events', NOW()),
       ('jI3iC_XkFz', 'Linus says: ''Look, the thing is''', 'Linus', NOW()),
       ('NW4TF_QlJS', 'Google News', 'Topics', NOW()),
       ('CEk26e6DFO', 'Videogame Topic', 'Topics', NOW()),
       ('kU6Q-jECe2', 'We''re Hiring', 'Events', NOW()),
       ('ALK9YM8Hm2', 'Linus calls someone live on show', 'Linus', NOW()),
       ('wcdAehN0u-', 'Linus explains how to human', 'Linus', NOW()),
       ('oZuNEsBKSV', 'Linus gets signed out of something', 'Linus', NOW()),
       ('wYu9kCUSEG', 'Linus mocks French people', 'Linus', NOW()),
       ('sxxPZxny2w', 'Luke talks about movies', 'Luke', NOW()),
       ('VX3l5edoJa', 'Dan mocks a file extension', 'Dan', NOW()),
       ('cDJ-tz58hc', 'Linus, Luke, or Dan make a terrible joke/pun', 'Events', NOW()),
       ('0_R_ptyCeC', 'Not Financial Advice', 'Events', NOW()),
       ('HbDcO3mpTN', 'Floatplane / Labs Preview', 'Topics', NOW()),
       ('etmSz-0MgR', 'Rapid-fire merch messages', 'Events', NOW()),
       ('AL0_lZxh-Q', 'Someone in the audience buys a domain', 'Events', NOW()),
       ('Xkq3e-6Efn', 'Linus Theft/Legal Tips', 'Events', NOW()),
       ('juZ0aAds-9', 'Linus talks about an upcoming product/video', 'Linus', NOW()),
       ('Ws6Y4nd9KB', 'Special Guest on Stream (Anyone but DLL)', 'Set/Production', NOW());