INSERT INTO tiles (id, text, category, weight, last_drawn_show)
VALUES ('pYhro7iTSQlbbMxdsg9J7', 'Linus or Luke or Dan sighs', 'Events', 1, NULL),
       ('3AXPH39mmUszzD_9Ttmfq', 'Linus ignores Luke to change the topic', 'Linus', 1, NULL),
       ('kJdmP6gDSijdSCqA-ptk6', 'Linus hates on Twitch Chat', 'Linus', 1, NULL),
       ('ji3eCBLPrxSrB9BOKG-bH', 'Linus Facepalms', 'Linus', 1, NULL),
       ('AQrAcWkqsg6ij4BwIBLRm', 'Intro/Outro run accidentally', 'Set/Production', 1, NULL),
       ('W9No_ylM54QsNxquFZbjd', 'The microphone gets hit', 'Set/Production', 1, NULL),
       ('OPdeRADtmKh1RHsmH22o9', '*Wow, I feel old...*', 'Events', 1, NULL),
       ('jXurzTPKY_2_BLYddQARX', 'Camera Not Focused', 'Set/Production', 1, NULL),
       ('GdOM4Jx7ZIeBsqlFEGzpf', 'Luke was Wrong', 'Luke', 1, NULL),
       ('WH6tzRJ5PGOAfupefdeXZ', 'Linus Was Wrong', 'Linus', 1, NULL),
       ('U3SEvAZT4EHVm1qbl1U8r', 'Colton Quit / Fired joke', 'Events', 1, NULL),
       ('kxR5uknbsW_ScyHM-oNVX', 'Linus Drops Something', 'Linus', 1, NULL),
       ('LdaAhl25W4KpvQEc_1Kzv', 'Nvidia News!', 'Topics', 1, NULL),
       ('BaD8f-Qmpgyx7_xH5vUir', 'AMD News!', 'Topics', 1, NULL),
       ('RubFqyA_Zs0XpwhZ0q_a5', 'Intel News!', 'Topics', 1, NULL),
       ('lovN9OEyXuC9PJQHnvnGb', 'Apple News!', 'Topics', 1, NULL),
       ('1zVBE4wLA9oQIWOvdjZIK', 'New Sponsor!', 'Sponsors', 1, NULL),
       ('3LHG-WTzBzDZbYu-HXoNh', 'Screenshare has No Audio', 'Set/Production', 1, NULL),
       ('fY2u7DoLZ7k5omiGY7eRZ', 'Audio Clipping', 'Set/Production', 1, NULL),
       ('sBbnG8b1O_4jy0WU0JYec', 'Literally one super topic until sponsor spot', 'Sponsors', 1, NULL),
       ('nc9JZl99MEJIDs1Cr1y_D', 'Linus leaves the other host alone', 'Linus', 1, NULL),
       ('JAgGIaNECUw8ivraJ0EXW', 'Video output not connected to laptop', 'Set/Production', 1, NULL),
       ('lND6zOabtjUV7fV-B3DiR', 'Console Topic for the peasantry', 'Topics', 1, NULL),
       ('eb8uFT5T_K0-befw40IBM', 'Luke says *That''s Hilarious!*', 'Luke', 1, NULL),
       ('17U6OdT6QW4WqrED_Ds0a', 'Someone messes with the set', 'Set/Production', 1, NULL),
       ('7zeqP0zUVdMnE7lCbElU7', 'Linus: ''We''ve got a great show for you today!''', 'Linus', 1, NULL),
       ('NZUFuGT4dgw3nbDoVBtUs', 'No actual news before sponsor spot', 'Sponsors', 1, NULL),
       ('uRE41fjRbKbHYD7Bal877', 'Linus doesn''t censor while swearing', 'Linus', 1, NULL),
       ('cjAULhjZBLZq0xzt-V_gV', 'Motion-Sickness Camera', 'Set/Production', 1, NULL),
       ('69LrHZvYtEuL8P4OdQhFs', 'Super-Zoomed Camera', 'Set/Production', 1, NULL),
       ('MdM9kwiAnaAQY2E_SVOae', 'Hello Dan', 'Dan', 1, NULL),
       ('i27fmnr_tu4nF4za9rWUr', 'LTT Store Plug', 'Events', 1, NULL),
       ('u5jjt2ruMPZEiIFrHDY9q', 'LTT Water Bottle drank from', 'Events', 1, NULL),
       ('JDJuwnV-OIV86l1Sm4mzK', 'Banana For Scale', 'Events', 1, NULL),
       ('ftsUAzY_Db6F5L76o8NXo', 'Linus Hot Take', 'Linus', 1, NULL),
       ('A6NucRK2Gj0xPFKLYfDxL', 'Linus Roasts a Company', 'Linus', 1, NULL),
       ('kJvJpGqFBVpGUgXwtmHIM', 'Linus'' parenting stories', 'Linus', 1, NULL),
       ('KsG42jyeJuixw0GM-O6ue', 'Mispronunciation of a word/phrase', 'Events', 1, NULL),
       ('I3GA3iJPjtzEP1_6kBnd_', 'Stream Dies', 'Events', 1, NULL),
       ('tj69a_JZfeIweQQrXbskV', 'Costumes!', 'Events', 1, NULL),
       ('BfaqFYztlR5Ix_l_hqCnB', '4+ Hour WAN Show (What a Champ!)', 'Events', 1, NULL),
       ('ASPY0Qy1tZDGmyNMTjnJc', 'Luke laughs uncomfortably loud', 'Luke', 1, NULL),
       ('2wN544Mxvc2TorepxLBTg', 'Luke talks about AI', 'Luke', 1, NULL),
       ('KKbzU2rbiJJkSBCn9duYF', 'Accidentally shared confidential info', 'Events', 1, NULL),
       ('W-motMP4ZsdIv3rkAKzok', 'Dan ignores Linus', 'Dan', 1, NULL),
       ('lqnGNVc9nttIrVhpiDdqc', 'Hit me Dan', 'Dan', 1, NULL),
       ('c7BjRI697FtIH2UJf4Idu', 'WANShow.bingo is mentioned', 'Events', 1, NULL),
       ('TBmEkuWwpRyCVLwpvaZ_l', 'Not my problem anymore, talk to the new ceo.', 'Events', 1, NULL),
       ('r9Mnf_ME0OHShfpeUVy-o', 'Linus: it''s not my fault', 'Linus', 1, NULL),
       ('8pce6MxeUuq31sjmZb_GI', 'Sponsored by dbrand!', 'Sponsors', 1, NULL),
       ('BlxEmS0DoW_U0m-iz7mdN', 'Sponsored by SquareSpace!', 'Sponsors', 1, NULL),
       ('73KLQbGb8qdAIV92l1hFA', 'Linus eats/drinks something', 'Linus', 1, NULL),
       ('sljhxujZPi9ltJOqFAp63', 'Linus complains about YouTube', 'Linus', 1, NULL),
       ('trAzkzKWLx6ZU42Mfor5g', 'Live Tech Product Unboxing', 'Events', 1, NULL),
       ('mfTNmsg6UIIzv5A4LvAyr', 'Talking over Audio', 'Set/Production', 1, NULL),
       ('WeV8Fp5qTkikUQUse1YmH', 'Trust me Bro', 'Events', 1, NULL),
       ('Qp6vz_-EADENmkwsyte6J', 'Linus is out of touch', 'Linus', 1, NULL),
       ('-Q5HcciRTECVS7cbAAT47', 'Too long (15 min+) on a topic', 'Events', 1, NULL),
       ('jjhqqMEYt7BKr85nCUO4P', 'Too long (5 mins+) on a merch message', 'Events', 1, NULL),
       ('kBkO1ou5Mgm-aDH2JPz_s', 'Innuendo', 'Events', 1, NULL),
       ('jEU-ZVrpBRU87a3R2ElrC', '*oh yeah I guess we should do sponsor spots*', 'Events', 1, NULL),
       ('BV1VTXBrjrBDVaXEsRPg4', 'Linus rants while Luke interacts with chat bored', 'Linus', 1, NULL),
       ('DEVW39oIdqYETocl_KIyI', 'Linus changes camera angle for dan ''I''ve got it''', 'Linus', 1, NULL),
       ('SSd2LAc9FQB6RS1V_Kwkz', 'Linus: ''Since you put me on the spot''', 'Linus', 1, NULL),
       ('qMU9ISD_9QxefzCdomAPq', 'New merch launch', 'Events', 1, NULL),
       ('HhLMpqN2FAkUIH4CmjTUV', 'Putting off Merch Messages ''We''ll get them in a sec''', 'Events', 1, NULL),
       ('bEFxAZvdfTaAR-UkD-BdQ', 'DAN tries to talk but is muted', 'Dan', 1, NULL),
       ('4ArJxjLxtvv0aLBF9pPAw', 'DING', 'Events', 1, NULL),
       ('Yyb48SI0jUfBUOD03LAn8', 'Dennis overboard sponsorspot', 'Sponsors', 1, NULL),
       ('ukjQJ5_-CKegKV6a_Og1q', 'Going back to previous topic/merch message', 'Events', 1, NULL),
       ('hQ3vMD9xNlj4sp2qEuRG2', '*The Hackening*', 'Events', 1, NULL),
       ('KeThW3a1tmwMrpefvVj60', 'Luke struggles to pick a topic', 'Luke', 1, NULL),
       ('23Cv4gW6DYocuVL_AgmUY', '*Spicy Take*', 'Events', 1, NULL),
       ('X_335PYYBnNUH80oHNDZ0', 'Dan cam with no Dan', 'Dan', 1, NULL),
       ('KVeHSSKAWkh9n5hOSvtkq', 'Dan goes and gets snacks for Linus', 'Dan', 1, NULL),
       ('Avkh2dEj_Roel6G2y55XO', 'Linus ''turns off'' Dan', 'Dan', 1, NULL),
       ('VKWvCKvn0srzyYYV9y_u4', '*Where was I going with this?*', 'Linus', 1, NULL),
       ('A4EhjSc-FeJm1kM8ujbiW', 'Luke doing a concern', 'Luke', 1, NULL),
       ('qvQmuF6SnJlZWHj5FdKBB', 'Linus rants for over 2 mins without input from Luke', 'Linus', 1, NULL),
       ('J6KHwBchwSD96UcFZ2D5_', 'Dan goes AFK', 'Dan', 1, NULL),
       ('W97lSUnnJbilKhUlqXSs0', 'Mentions another creator', 'Events', 1, NULL),
       ('jI3iC_XkFzfwFEPTP8U8u', 'Linus says: ''Look, the thing is''', 'Linus', 1, NULL),
       ('NW4TF_QlJS48JR5aKOiWL', 'Google News', 'Topics', 1, NULL),
       ('CEk26e6DFOQUXOaZVaOH0', 'Videogame Topic', 'Topics', 1, NULL),
       ('kU6Q-jECe2jPGeA97mb96', 'We''re Hiring', 'Events', 1, NULL),
       ('ALK9YM8Hm2xmya4QWbX4s', 'Linus calls someone live on show', 'Linus', 1, NULL),
       ('wcdAehN0u-u8Cnle19JeD', 'Linus explains how to human', 'Linus', 1, NULL),
       ('oZuNEsBKSVbIEmoMa_Auw', 'Linus gets signed out of something', 'Linus', 1, NULL),
       ('wYu9kCUSEGeC9VZfA8U71', 'Linus mocks French people', 'Linus', 1, NULL),
       ('sxxPZxny2wb8MgqdXmONG', 'Luke talks about movies', 'Luke', 1, NULL),
       ('VX3l5edoJaTw-Waobpwbk', 'Dan mocks a file extension', 'Dan', 1, NULL),
       ('cDJ-tz58hcuJJzndh9xQd', 'Linus, Luke, or Dan make a terrible joke/pun', 'Events', 1, NULL),
       ('0_R_ptyCeCXJ0EQfAoWCO', 'Not Financial Advice', 'Events', 1, NULL),
       ('HbDcO3mpTNj93tE_XP-2P', 'Floatplane / Labs Preview', 'Topics', 1, NULL),
       ('etmSz-0MgRaBrU85nI6io', 'Rapid-fire merch messages', 'Events', 1, NULL),
       ('AL0_lZxh-QmfXZ4mdhwEr', 'Someone in the audience buys a domain', 'Events', 1, NULL),
       ('Xkq3e-6EfnBD95J1EAilM', 'Linus Theft/Legal Tips', 'Events', 1, NULL),
       ('juZ0aAds-9L2NmO2_7Fbu', 'Linus talks about an upcoming product/video', 'Linus', 1, NULL),
       ('Ws6Y4nd9KBhr2PXaQspBJ', 'Special Guest on Stream (Anyone but DLL)', 'Set/Production', 1, NULL);


INSERT INTO players (id, wos_id, display_name, settings, permissions)
VALUES ('4r1BG0aYrH', 'user_01K7AS90P91AR3TNS2MRBTEKS4', 'Altrius', '{"chat_color": "#9600ff"}', 0);