name: Build and Push Docker Images

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set OWNER_LC
        run: echo "OWNER_LC=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Check for changes
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            frontend:
              - 'frontend/**'
            server:
              - 'server/**'

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push frontend image
        if: github.ref_type == 'tag' || steps.filter.outputs.frontend == 'true'
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          build-args: |
            NEXT_PUBLIC_API_ROOT=${{ secrets.NEXT_PUBLIC_API_ROOT }}
          tags: |
            ghcr.io/${{ env.OWNER_LC }}/wanbingo-frontend:latest
            ghcr.io/${{ env.OWNER_LC }}/wanbingo-frontend:${{ github.sha }}

      - name: Build and push server image
        if: github.ref_type == 'tag' || steps.filter.outputs.server == 'true'
        uses: docker/build-push-action@v5
        with:
          context: ./server
          push: true
          tags: |
            ghcr.io/${{ env.OWNER_LC }}/wanbingo-api:latest
            ghcr.io/${{ env.OWNER_LC }}/wanbingo-api:${{ github.sha }}
