name: Build and Push Docker Images

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      frontend: ${{ steps.filter.outputs.frontend }}
      server: ${{ steps.filter.outputs.server }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Check for changes
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            frontend:
              - 'frontend/**'
            server:
              - 'server/**'

  build-frontend:
    runs-on: ubuntu-latest
    needs: check-changes
    if: github.ref_type == 'tag' || needs.check-changes.outputs.frontend == 'true'
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set OWNER_LC
        run: echo "OWNER_LC=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          build-args: |
            NEXT_PUBLIC_API_ROOT=${{ secrets.NEXT_PUBLIC_API_ROOT }}
          tags: |
            ghcr.io/${{ env.OWNER_LC }}/wanbingo-frontend:latest
            ghcr.io/${{ env.OWNER_LC }}/wanbingo-frontend:${{ github.sha }}

  build-server:
    runs-on: ubuntu-latest
    needs: check-changes
    if: github.ref_type == 'tag' || needs.check-changes.outputs.server == 'true'
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set OWNER_LC
        run: echo "OWNER_LC=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push server image
        uses: docker/build-push-action@v5
        with:
          context: ./server
          push: true
          tags: |
            ghcr.io/${{ env.OWNER_LC }}/wanbingo-api:latest
            ghcr.io/${{ env.OWNER_LC }}/wanbingo-api:${{ github.sha }}
